# .github/workflows/community.yml
name: Blabeley

on:
  issues:
    types: [opened, edited, unlabeled]
  pull_request_target:
    types: [opened, edited, unlabeled, synchronize]

jobs:
  label-issues-and-prs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Apply labels based on config
        uses: jimschubert/labeler-action@v2
        with:
          config_path: '.github/workflows/labeler.yml'
          github-token: ${{ secrets.GITHUB_TOKEN }}
