# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    I smelt your issue and found some suitable tags! 
    
    Thank you for submitting this issue! Please wait for someone to respond to this issue.
  prs: |
    I smelt your pull request and found some suitable tags!

    Thank you for your contributions! They will be appreciated, even if not accpeted!
    
# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
#    - 'branches' is an optional array of branch names (or patterns) to limit labeling according to PR target branch
labels:
  'bug in my Tea':
    include:
      - '\bbug[s]?\b'
    exclude: []
    branches:
      - 'master'
      - 'main'
  'need some help':
    include:
      - '\bhelp( me)?\b'
    exclude:
      - '\b\[test(ing)?\]\b'
  'a new Teabag':
    include:
      - '\bfeat\b'
    exclude: []
  'how to drink Tea':
    include:
      - '\b.md\b'
    exclude: []
